pipeline { 
    agent {
        docker { image 'node:14-alpine' }
    }
    stages {
        stage('Build') { 
            steps { 
                echo "Building..."
                sh 'apt install git -y'
            }
        }
        stage('Test'){
            steps {
                echo "Testing..." 
                sh 'apt install nodejs -y'
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying..."
                sh 'apt install npm -y'
                echo "Finished!"
               
            }
        }
    }
}
